### ISSUE TITLE
Feedback on sorting algorithms

### ISSUE THREAD

**Issue by Anisha7** [jshams/CS-2.1-Trees-Sorting#1]
What was great:
- Good job on implementing your is_sorting function efficiently!
- Good job on successfully implementing your sorting algorithms and completing stretch challenges!

Here's some feedback to improve:
- Typo in split_sort_merge: `middle = len(items // 2)` should be `middle = len(items)//2`

**Comment by jshams** [comment]
Thanks for the feedback! Good catch as well. I've updated the code to work properly.
